keep-open=yes
keep-open-pause=no

script-opts=console-scale=1.5

# Remember playing position
save-position-on-quit=yes
watch-later-options=vid,aid,sid

# Screenshot
screenshot-directory="~~desktop/"
screenshot-format=png

# Boost opening time
icc-cache-dir="~~/cache/icc"
gpu-shader-cache-dir="~~/cache/shaders"

# Load external subtitles and audios
sub-auto=fuzzy
audio-file-auto=fuzzy

# Colored message
msg-color=yes
term-osd-bar=yes

# Cache
cache=yes
cache-secs=30
demuxer-max-bytes=1800M
demuxer-max-back-bytes=1200M

# Video
vo=gpu-next
profile=gpu-hq
hwdec=nvdec-copy
hwdec-codecs=all
gpu-api=vulkan

# From VCB-Studio
icc-profile-auto=yes # 色彩管理
blend-subtitles=video # 将字幕渲染到视频源分辨率并随视频一起缩放并进行色彩管理
scale=ewa_lanczos # 进一步提高画面拉伸质量，可以将画面拉伸算法更改为 EWA Lanczos
scale-blur=0.981251

# Interpolation
video-sync=display-resample
interpolation=yes
tscale=oversample # smoothmotion

# Preferred subtitle
slang=chs,chi,zh,cn

# Default font for subtitle
sub-font='Source Han Sans Regular'

# Interface
# https://github.com/tomasklaen/uosc
# required so that the 2 UIs don't fight each other
osc=no
# uosc provides its own seeking/volume indicators, so you also don't need this
osd-bar=no
# uosc will draw its own window controls if you disable window border
border=no
